### ISSUE TITLE
Heavy SQL

### ISSUE THREAD

**Issue by Leinad4Mind** [ForumHulp/pmspy#10]
Hi there, now and then when I click on PM Spy at ACP I get this error (But if I click again on pm spy the problem doesnt appear since it seems to use cache, but after some time later it crashes, but it is always on the 1st time I try to open):

SQL ERROR [ mysqli ]

Server shutdown in progress [1053]

SQL

SELECT p.msg_id, p.message_subject, p.message_text, p.bbcode_uid, p.bbcode_bitfield, p.message_time, p.bcc_address, p.to_address, p.author_ip, t.user_id, t.author_id, t.folder_id FROM phpbb_privmsgs_to t LEFT JOIN phpbb_privmsgs p ON p.msg_id = t.msg_id LEFT JOIN phpbb_users u ON u.user_id = t.user_id LEFT JOIN phpbb_users uu ON uu.user_id = t.author_id ORDER BY p.message_time DESC LIMIT 30

It seems 3 left join are overkill. I didnt had time to dig on this sql. But I'll let the issue here in case you or any other may have another approach.

EDIT: I got some time now and decided to make a try and to remove the left joins and use only where clause:

`$sql = 'SELECT p.msg_id, p.message_subject, p.message_text, p.bbcode_uid, p.bbcode_bitfield, p.message_time, p.bcc_address, p.to_address, p.author_ip, t.user_id,
					t.author_id, t.folder_id
					FROM ' . PRIVMSGS_TO_TABLE . ' t, ' . PRIVMSGS_TABLE . ' p, ' . USERS_TABLE . ' u, ' . USERS_TABLE . ' uu
					WHERE p.msg_id = t.msg_id 
					AND u.user_id = t.user_id
					AND uu.user_id = t.author_id
					' . $sql_keywords . ' ' .
				//		$order_sql . '
					' ORDER BY ' . $order_by;`

It goes from 2s from 0.002s to execute, but I need to see if I am losing any kind of record, but it should be it.
For what I saw the current SQL gives as result some trash that should not appear when we order fields: https://i.imgur.com/Nrbgwn0.png

With my sql above it fixes that bug too.

You can see by the pm count. On my case: PM count: 123921

And when I run this sql at phpmyadmin:
`SELECT p.msg_id, p.message_subject, p.message_text, p.bbcode_uid, p.bbcode_bitfield, p.message_time, p.bcc_address, p.to_address, p.author_ip, t.user_id,
					t.author_id, t.folder_id
					FROM phpbb_privmsgs_to t, phpbb_privmsgs p, phpbb_users u, phpbb_users uu
					WHERE p.msg_id = t.msg_id 
					AND u.user_id = t.user_id
					AND uu.user_id = t.author_id
					ORDER BY p.message_time DESC;`

Showing records 0 - 29 (123920 total, querie took 0.0022 seconds.) [message_time: 1570351215... - 1570053226...]

And when running this:
`
SELECT p.msg_id, p.message_subject, p.message_text, p.bbcode_uid, p.bbcode_bitfield, p.message_time, p.bcc_address, p.to_address, p.author_ip, t.user_id,
					t.author_id, t.folder_id
					FROM phpbb_privmsgs_to t
					LEFT JOIN phpbb_privmsgs p ON p.msg_id = t.msg_id 
					LEFT JOIN phpbb_users u ON u.user_id = t.user_id
					LEFT JOIN phpbb_users uu ON uu.user_id = t.author_id
					ORDER BY p.message_time DESC`

Message was:
Showing records 0 - 29 (168713 total, querie took 2.5023 seconds.) [message_time: 1570351215... - 1570053226...]

So with this sql fixed it will be a lot more quick to perform and with almost the correct total number of records, we're losing 1 record... lol

EDIT 2:

I've recheck your sql again and could find the issue, one of the left joins should be right join:

`SELECT p.msg_id, p.message_subject, p.message_text, p.bbcode_uid, p.bbcode_bitfield, p.message_time, p.bcc_address, p.to_address, p.author_ip, t.user_id, t.author_id, t.folder_id
FROM phpbb_privmsgs_to t
RIGHT JOIN phpbb_privmsgs p ON p.msg_id = t.msg_id 
LEFT JOIN phpbb_users u ON u.user_id = t.user_id 
LEFT JOIN phpbb_users uu ON uu.user_id = t.author_id
ORDER BY p.message_time DESC`

Like this all solved :) And it matches the number of records

**Comment by ForumHulp** [comment]
Thanks
