### ISSUE TITLE
Search Pagination

### ISSUE THREAD

**Issue by DigitalFuturePT** [ForumHulp/pmspy#4]
Hi there, 

thks a lot for the search feature.

There is just a little bug on the pagination. It stop working. Before and after the search.

**Comment by ForumHulp** [comment]
Thanks TarantinoMariachi  
Seems like a bug in phpbb. it places the sid double in baseurl. 
Can you check if all is working ok, then we create a ticket in phpbb

**Comment by DigitalFuturePT** [comment]
Thks it worked.

Now I changed the 3 to 30: $this->config['topics_per_page'] = 3;

**Comment by ForumHulp** [comment]
Thanks for testing, the config per page is removed. It should not be there.
So we found a bug in phpbb

https://www.phpbb.com/community/viewtopic.php?f=466&t=2467576
