### ISSUE TITLE
PM Spy only for founder

### ISSUE THREAD

**Issue by SpIdErPiGgY1984** [ForumHulp/pmspy#8]
This is a great ext, but I don't like it that all my admins can read the PM's. Is it possible to only show this ext to founders, or just a user ID ?

**Comment by ForumHulp** [comment]
What you could do is this:
Disable en delete data in extensionmanager. 
Change in pmspy_info.php line23 in 
					'auth'	=> 'ext_forumhulp/pmspy && acl_a_aauth',
Save and enable the extension again.

**Comment by SpIdErPiGgY1984** [comment]
acl_a_aauth is for all admins. I need something to show it only to founders, or 2 users ID's

**Comment by ForumHulp** [comment]
Use a permission you admins don't have permission for. I can not see what your admins don't have permissions for.

**Comment by SpIdErPiGgY1984** [comment]
Ah I see, found it. Works :) Thank you
